// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Simpbot.Core.Persistence;
using System;

namespace Simpbot.Core.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20180508114020_PrefixMixingMigration")]
    partial class PrefixMixingMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Simpbot.Core.Persistence.Entity.Muted", b =>
                {
                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("UserId");

                    b.Property<bool>("IsMuted");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("Muteds");
                });

            modelBuilder.Entity("Simpbot.Core.Persistence.Entity.Prefix", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<char>("PrefixSymbol");

                    b.HasKey("GuildId");

                    b.ToTable("Prefixes");
                });
#pragma warning restore 612, 618
        }
    }
}
