// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Simpbot.Core.Persistence;
using System;

namespace Simpbot.Core.Migrations
{
    [DbContext(typeof(PrefixContext))]
    partial class PrefixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Simpbot.Core.Persistence.Entity.Prefix", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<char>("PrefixSymbol");

                    b.HasKey("GuildId");

                    b.ToTable("Prefixes");
                });

            modelBuilder.Entity("Simpbot.Core.Persistence.Entity.PrefixDefault", b =>
                {
                    b.Property<char>("PrefixId")
                        .ValueGeneratedOnAdd();

                    b.Property<char>("PrefixSymbol");

                    b.HasKey("PrefixId");

                    b.ToTable("PrefixDefaults");
                });
#pragma warning restore 612, 618
        }
    }
}
